import ml_server
print('Training attendance')
ml_server.train_attendance()
print('Training availability')
ml_server.train_availability()
print('Training demand')
ml_server.train_demand()
print('Training skill')
ml_server.train_skill()
print('Training fraud')
ml_server.train_fraud()
print('Training wage')
ml_server.train_wage()
print('Done training!')
